#!/usr/bin/env bash
#
# Generate the release-candidate report from GitHub state.
#
# Usage:
#   scripts/rc-report.sh            # resolve the open RC milestone automatically
#   scripts/rc-report.sh v1.1.0     # report on a specific RC
#   scripts/rc-report.sh v1.1.0 -   # write to stdout instead of a file
#
# The report is derived, never hand-written: issues come from the tracker
# milestone, changes come from PRs actually merged into the RC branch of each
# repository. Rollout order is a fixed dependency chain, filtered to the
# repositories that actually have changes.

set -euo pipefail

TRACKER="speq-tms/speq-docs"
ORG="speq-tms"

# Rollout order is a dependency chain, not a preference:
#   contracts define the schemas everything else validates against;
#   cli implements them; examples prove the cli against a real API;
#   the runner wraps a published cli; the tap needs a published release to
#   point at; docs describe what shipped; the site publishes them.
ROLLOUT=(speq-contracts speq-cli speq-examples speq-github-runner homebrew-tap speq-docs speq-tms.github.io)

RC="${1:-}"
OUT="${2:-}"

if [[ -z "$RC" ]]; then
  RC="$(gh api "repos/$TRACKER/milestones" \
    --jq '[.[] | select(.state=="open" and .title != "backlog") | .title] | first // empty')"
  [[ -n "$RC" ]] || { echo "no open RC milestone in $TRACKER; pass one explicitly" >&2; exit 1; }
fi

milestone_json="$(gh api "repos/$TRACKER/milestones" \
  --jq "[.[] | select(.title == \"$RC\")] | first // empty")"
[[ -n "$milestone_json" ]] || { echo "milestone '$RC' not found in $TRACKER" >&2; exit 1; }

open_count="$(jq -r '.open_issues' <<<"$milestone_json")"
closed_count="$(jq -r '.closed_issues' <<<"$milestone_json")"
total=$((open_count + closed_count))

emit() {
  echo "# Release candidate $RC"
  echo
  echo "Generated by \`scripts/rc-report.sh\` from GitHub state on $(date -u '+%Y-%m-%d %H:%M UTC')."
  echo "Do not edit by hand — regenerate instead."
  echo
  echo "Progress: **$closed_count of $total** issues closed."
  echo

  echo "## Scope"
  echo
  echo "Issues on milestone \`$RC\` in [\`$TRACKER\`](https://github.com/$TRACKER/issues)."
  echo
  echo "| Issue | Area | State | Title |"
  echo "| --- | --- | --- | --- |"
  gh issue list --repo "$TRACKER" --milestone "$RC" --state all --limit 200 \
    --json number,title,state,labels \
    --jq '.[] | "| #\(.number) | \([.labels[].name | select(startswith("area/"))] | join(", ") // "—") | \(if .state == "CLOSED" then "closed" else "open" end) | \(.title) |"'
  echo

  echo "## Changes per repository"
  echo
  local any=0
  for repo in "${ROLLOUT[@]}"; do
    local has_rc prs
    has_rc=""
    # Exit code only: on a missing branch `gh api` writes the error body to
    # stdout, so a non-empty result does not mean the branch exists.
    gh api "repos/$ORG/$repo/branches/$RC" >/dev/null 2>&1 && has_rc="$RC"
    prs="$(gh pr list --repo "$ORG/$repo" --base "$RC" --state merged --limit 100 \
      --json number,title,mergedAt \
      --jq '.[] | "- [#\(.number)](https://github.com/'"$ORG"'/'"$repo"'/pull/\(.number)) \(.title)"' 2>/dev/null || true)"

    [[ -z "$has_rc" && -z "$prs" ]] && continue
    any=1

    echo "### $repo"
    echo
    if [[ -z "$has_rc" ]]; then
      echo "No \`$RC\` branch. Nothing staged for this release."
    elif [[ -z "$prs" ]]; then
      echo "Branch \`$RC\` exists, no PRs merged into it yet."
    else
      echo "$prs"
    fi
    echo
  done
  [[ "$any" == 1 ]] || echo "_No repository has an \`$RC\` branch yet._"

  echo "## Rollout order"
  echo
  echo "Merge each RC into \`main\` in this order, and only after every issue on the milestone is closed."
  echo "The order is a dependency chain, not a preference."
  echo
  local n=0
  for repo in "${ROLLOUT[@]}"; do
    gh api "repos/$ORG/$repo/branches/$RC" >/dev/null 2>&1 || continue
    n=$((n + 1))
    case "$repo" in
      speq-contracts) why="schemas everything else validates against" ;;
      speq-cli) why="runtime; must match the contracts above" ;;
      speq-examples) why="acceptance gate; proves the cli against a real API" ;;
      speq-github-runner) why="wraps a published cli" ;;
      homebrew-tap) why="must point at an already published release artifact" ;;
      speq-docs) why="documents what actually shipped" ;;
      speq-tms.github.io) why="publishes the documentation" ;;
      *) why="" ;;
    esac
    echo "$n. **$repo** — $why"
  done
  echo
  echo "> \`homebrew-tap\` must not be merged before the \`speq-cli\` release artifact exists."
  echo "> In \`speq-cli\`, merging a branch whose name starts with \`v\` into \`main\` triggers the release build."
  echo
  echo "## Release gates"
  echo
  echo "- [ ] Every issue on milestone \`$RC\` is closed"
  echo "- [ ] \`cargo build && cargo test\` green in \`speq-cli\`"
  echo "- [ ] \`speq-examples/test-repo-mode-jsonplaceholder\` reports \`\"failed\": 0\`"
  echo "- [ ] Every new feature has an acceptance example"
  echo "- [ ] Documentation matches implemented behavior"
  echo "- [ ] Contracts aligned across \`speq-cli\`, \`speq-contracts\`, \`speq-vscode-extension\`"
}

if [[ "$OUT" == "-" ]]; then
  emit
else
  target="${OUT:-docs/delivery/rc/$RC.md}"
  mkdir -p "$(dirname "$target")"
  emit > "$target"
  echo "wrote $target" >&2
fi
